"""One-time lookup snapshot from the workbook tables; app runtime uses SQLite."""

COMMON_DROP_ORDER = ['Slime',
 'Hilichurl',
 'Samachurl',
 'Hilichurl Shooter',
 'Fatui',
 'Treasure Hoarder',
 'Whopperflower',
 'Nobushi',
 'Specter',
 'Floating Fungi',
 'Eremite',
 'Fontemer Aberrant',
 'Clockwork Meka',
 'Saurian',
 'Sauroform Tribal Warrior']

ELITE_DROP_ORDER = ['Mitachurl',
 'Abyss Mage',
 'Ruin Machine 1',
 'Fatui Cicin Mage',
 'Fatui Agent',
 'Vishap',
 'Ruin Machine 2',
 'Mirror Maiden',
 'Rifthound',
 'Shadowy Husk',
 'Ruin Machine 3',
 'Activated Fungi',
 'Primal Construct',
 'Consecrated Beast',
 'Hilichurl Rogue',
 'Tainted Hydro Phantasm',
 'Breacher Primus',
 'Fatui Operative',
 'Xuanwen Beast',
 'Golem Guard',
 'Wayob Manifestation',
 'Avatar of Lava',
 'Secret Source Automaton',
 'Tenebrous Mimiflora',
 'Furnace Shell Mountain Weasel']

WEEKLY_BOSS_TYPES = [('Dvalin 1', "Dvalin's Plume"),
 ('Dvalin 2', "Dvalin's Claw"),
 ('Dvalin 3', "Dvalin's Sigh"),
 ('Boreas 1', 'Tail of Boreas'),
 ('Boreas 2', 'Ring of Boreas'),
 ('Boreas 3', 'Spirit Locket of Boreas'),
 ('Childe 1', 'Tusk of Monoceros Caeli'),
 ('Childe 2', 'Shard of a Foul Legacy'),
 ('Childe 3', 'Shadow of the Warrior'),
 ('Azhdaha 1', "Dragon Lord's Crown"),
 ('Azhdaha 2', 'Bloodjade Branch'),
 ('Azhdaha 3', 'Gilded Scale'),
 ('Signora 1', 'Molten Moment'),
 ('Signora 2', 'Hellfire Butterfly'),
 ('Signora 3', 'Ashen Heart'),
 ('Raiden 1', 'Mudra of the Malefic General'),
 ('Raiden 2', 'Tears of the Calamitous God'),
 ('Raiden 3', 'The Meaning of Aeons'),
 ('Scaramouche 1', 'Puppet Strings'),
 ('Scaramouche 2', 'Mirror of Mushin'),
 ('Scaramouche 3', "Daka's Bell"),
 ('Apep 1', 'Worldspan Fern'),
 ('Apep 2', 'Primordial Greenbloom'),
 ('Apep 3', 'Everamber'),
 ('Narwhal 1', 'Lightless Silk String'),
 ('Narwhal 2', 'Lightless Eye of the Maelstrom'),
 ('Narwhal 3', 'Lightless Mass'),
 ('Knave 1', 'Fading Candle'),
 ('Knave 2', 'Silken Feather'),
 ('Knave 3', 'Denial and Judgment'),
 ('Eroded Primal Fire 1', 'Eroded Horn'),
 ('Eroded Primal Fire 2', 'Eroded Sunfire'),
 ('Eroded Primal Fire 3', 'Eroded Scale-Feather'),
 ('Game before the Gate 1', 'Ascended Sample: Knight'),
 ('Game before the Gate 2', 'Ascended Sample: Rook'),
 ('Game before the Gate 3', 'Ascended Sample: Queen')]

TALENT_BOOK_ORDER = ['Mondstadt 1',
 'Mondstadt 2',
 'Mondstadt 3',
 'Liyue 1',
 'Liyue 2',
 'Liyue 3',
 'Inazuma 1',
 'Inazuma 2',
 'Inazuma 3',
 'Sumeru 1',
 'Sumeru 2',
 'Sumeru 3',
 'Fontaine 1',
 'Fontaine 2',
 'Fontaine 3',
 'Natlan 1',
 'Natlan 2',
 'Natlan 3',
 'Nod Krai 1',
 'Nod Krai 2',
 'Nod Krai 3']

WEAPON_ASCENSION_ORDER = ['Mondstadt 1',
 'Mondstadt 2',
 'Mondstadt 3',
 'Liyue 1',
 'Liyue 2',
 'Liyue 3',
 'Inazuma 1',
 'Inazuma 2',
 'Inazuma 3',
 'Sumeru 1',
 'Sumeru 2',
 'Sumeru 3',
 'Fontaine 1',
 'Fontaine 2',
 'Fontaine 3',
 'Natlan 1',
 'Natlan 2',
 'Natlan 3',
 'Nod Krai 1',
 'Nod Krai 2',
 'Nod Krai 3']
