"""Material display order snapshot from workbook lookup and Overview sheets."""

MATERIAL_ORDER = {'common_drop': ['Slime Condensate',
                 'Slime Secretions',
                 'Slime Concentrate',
                 'Damaged Mask',
                 'Stained Mask',
                 'Ominous Mask',
                 'Divining Scroll',
                 'Sealed Scroll',
                 'Forbidden Scroll',
                 'Firm Arrowhead',
                 'Sharp Arrowhead',
                 'Weathered Arrowhead',
                 "Recruit's Insignia",
                 "Sergeant's Insignia",
                 "Lieutenant's Insignia",
                 'Treasure Hoarder Insignia',
                 'Silver Raven Insignia',
                 'Golden Raven Insignia',
                 'Whopperflower',
                 'Shimmering Nectar',
                 'Energy Nectar',
                 'Old Nobushi',
                 'Kageuchi Nobushi',
                 'Famed Nobushi',
                 'Spectral Husk',
                 'Spectral Heart',
                 'Spectral Nucleus',
                 'Fungal Spores',
                 'Luminescent Pollen',
                 'Crystalline Cyst Dust',
                 'Faded Red Satin',
                 'Trimmed Red Silk',
                 'Rich Red Brocade',
                 'Transoceanic Pearl',
                 'Transoceanic Chunk',
                 'Xenochromatic Crystal',
                 'Clockwork Meka',
                 'Mechanical Spur Gear',
                 'Artificed Dynamic Gear',
                 'Juvenile Fang',
                 'Seasoned Fang',
                 'Tyrant’s Fang',
                 'Sentry’s Wooden Whistle',
                 'Warrior’s Metal Whistle',
                 'Saurian-Crowned Warrior’s Golden Whistle'],
 'elite_drop': ['Heavy Horn',
                'Black Bronze Horn',
                'Black Crystal Horn',
                'Dead Ley Line Branch',
                'Dead Ley Line Leaves',
                'Ley Line Sprouts',
                'Chaos Device',
                'Chaos Circuit',
                'Chaos Core',
                'Mist Grass Pollen',
                'Mist Grass',
                'Mist Grass Wick',
                "Hunter's Sacrificial Knife",
                "Agent's Sacrificial Knife",
                "Inspector's Sacrificial Knife",
                'Fragile Bone Shard',
                'Sturdy Bone Shard',
                'Fossilized Bone Shard',
                'Chaos Gear',
                'Chaos Axis',
                'Chaos Oculus',
                'Dismal Prism',
                'Crystal Prism',
                'Polarizing Prism',
                'Concealed Rifthound',
                'Concealed Unguis',
                'Concealed Talon',
                'Gloomy Shadowy Husk',
                'Dark Shadowy Husk',
                'Deathly Shadowy Husk',
                'Chaos Storage',
                'Chaos Module',
                'Chaos Bolt',
                'Inactivated Activated Fungi',
                'Dormant Activated Fungi',
                'Robust Activated Fungi',
                'Damaged Prism',
                'Turbid Prism',
                'Radiant Prism',
                'Desiccated Shell',
                'Sturdy Shell',
                'Marked Shell',
                'A Flower Yet to Bloom',
                'Treasured Flower',
                "Wanderer's Blooming Flower",
                'Drop of Tainted Water',
                'Scoop of Tainted Water',
                'Newborn Tainted Hydro Eidolon',
                'Rift Core',
                'Foreign Synapse',
                'Alien Life Core',
                "Old Operative's Pocket Watch",
                "Operative's Standard Pocket Watch",
                "Operative's Constancy",
                'Feathery Fin',
                'Lunar Fin',
                'Chasmlight Fin',
                'Ruined Hilt',
                'Splintered Hilt',
                'Still-Smoldering Hilt',
                'Shard of a Shattered Will',
                'Locus of a Clear Will',
                'Sigil of a Striding Will',
                'Ignited Stone',
                'Ignited Seed of Life',
                'Ignited Seeing Eye',
                'Axis of the Secret Source',
                'Sheath of the Secret Source',
                'Heart of the Secret Source',
                'Refractive Bud',
                'Bewildering Broadleaf',
                'Illusory Leafcoil',
                'Cold-Cracked Shellshard',
                'Warm Back-Shell',
                'Blazing Prismshell'],
 'talent_book': ['Teachings of Freedom',
                 'Guide to Freedom',
                 'Philosophies of Freedom',
                 'Teachings of Resistance',
                 'Guide to Resistance',
                 'Philosophies of Resistance',
                 'Teachings of Ballad',
                 'Guide to Ballad',
                 'Philosophies of Ballad',
                 'Teachings of Prosperity',
                 'Guide to Prosperity',
                 'Philosophies of Prosperity',
                 'Teachings of Diligence',
                 'Guide to Diligence',
                 'Philosophies of Diligence',
                 'Teachings of Gold',
                 'Guide to Gold',
                 'Philosophies of Gold',
                 'Teachings of Transience',
                 'Guide to Transience',
                 'Philosophies of Transience',
                 'Teachings of Elegance',
                 'Guide to Elegance',
                 'Philosophies of Elegance',
                 'Teachings of Light',
                 'Guide to Light',
                 'Philosophies of Light',
                 'Teachings of Admonition',
                 'Guide to Admonition',
                 'Philosophies of Admonition',
                 'Teachings of Ingenuity',
                 'Guide to Ingenuity',
                 'Philosophies of Ingenuity',
                 'Teachings of Praxis',
                 'Guide to Praxis',
                 'Philosophies of Praxis',
                 'Teachings of Equity',
                 'Guide to Equity',
                 'Philosophies of Equity',
                 'Teachings of Justice',
                 'Guide to Justice',
                 'Philosophies of Justice',
                 'Teachings of Order',
                 'Guide to Order',
                 'Philosophies of Order',
                 'Teachings of Contention',
                 'Guide to Contention',
                 'Philosophies of Contention',
                 'Teachings of Kindling',
                 'Guide to Kindling',
                 'Philosophies of Kindling',
                 'Teachings of Conflict',
                 'Guide to Conflict',
                 'Philosophies of Conflict',
                 'Teachings of Moonlight',
                 'Guide to Moonlight',
                 'Philosophies of Moonlight',
                 'Teachings of Elysium',
                 'Guide to Elysium',
                 'Philosophies of Elysium',
                 'Teachings of Vagrancy',
                 'Guide to Vagrancy',
                 'Philosophies of Vagrancy'],
 'weapon_ascension': ["Tile of Decarabian's Tower",
                      "Debris of Decarabian's City",
                      "Fragment of Decarabian's Epic",
                      "Scattered Piece of Decarabian's Dream",
                      "Boreal Wolf's Milk Tooth",
                      "Boreal Wolf's Cracked Tooth",
                      "Boreal Wolf's Broken Fang",
                      "Boreal Wolf's Nostalgia",
                      'Fetters of the Dandelion Gladiator',
                      'Chains of the Dandelion Gladiator',
                      'Shackles of the Dandelion Gladiator',
                      'Dream of the Dandelion Gladiator',
                      'Luminous Sands from Guyun',
                      'Lustrous Stone from Guyun',
                      'Relic from Guyun',
                      'Divine Body from Guyun',
                      'Mist Veiled Lead Elixir',
                      'Mist Veiled Mercury Elixir',
                      'Mist Veiled Gold Elixir',
                      'Mist Veiled Primo Elixir',
                      'Grain of Aerosiderite',
                      'Piece of Aerosiderite',
                      'Bit of Aerosiderite',
                      'Chunk of Aerosiderite',
                      'Coral Branch of a Distant Sea',
                      'Jeweled Branch of a Distant Sea',
                      'Jade Branch of a Distant Sea',
                      'Golden Branch of a Distant Sea',
                      "Narukami's Wisdon",
                      "Narukami's Joy",
                      "Narukami's Affection",
                      "Narukami's Valor",
                      'Mask of the Wicked Lieutenant',
                      "Mask of the Tiger's Bite",
                      'Mask of the One-Horned',
                      'Mask of the Kijin',
                      'Copper Talisman of the Forest Dew',
                      'Iron Talisman of the Forest Dew',
                      'Silver Talisman of the Forest Dew',
                      'Golden Talisman of the Forest Dew',
                      "Oasis Garden's Reminiscence",
                      "Oasis Garden's Kindness",
                      "Oasis Garden's Mourning",
                      "Oasis Garden's Truth",
                      'Echo of Scorching Might',
                      'Remnant Glow of Scorching Might',
                      'Dream of Scorching Might',
                      'Olden Days of Scorching Might',
                      'Fragment of an Ancient Chord',
                      'Chapter of an Ancient Chord',
                      'Movement of an Ancient Chord',
                      'Echo of an Ancient Chord',
                      'Dross of Pure Sacred Dewdrop',
                      'Sublimation of Pure Sacred Dewdrop',
                      'Spring of Pure Sacred Dewdrop',
                      'Essense of Pure Sacred Dewdrop',
                      'Broken Goblet of the Pristine Sea',
                      'Wine Goblet of the Pristine Sea',
                      'Silver Goblet of the Pristine Sea',
                      'Golden Goblet of the Pristine Sea',
                      "Blazing Sacrificial Heart's Terror",
                      "Blazing Sacrificial Heart's Hesitance",
                      "Blazing Sacrificial Heart's Resolve",
                      "Blazing Sacrificial Heart's Splendor",
                      'Delirious Decadence of the Sacred Lord',
                      'Delirious Desolation of the Sacred Lord',
                      'Delirious Demeanor of the Sacred Lord',
                      'Delirious Divinity of the Sacred Lord',
                      "Night-Wind's Mystic Consideration",
                      "Night-Wind's Mystic Premonition",
                      "Night-Wind's Mystic Augury",
                      "Night-Wind's Mystic Revelation",
                      'Mysterious Instrument Fragment',
                      'Mysterious Instrument Replica',
                      'Inheritance of the Tricky Instrument\t',
                      "Whimsical Instrument's Trusty Wish",
                      'Ember of Long Night Flint',
                      'Afterglow of Long Night Flint',
                      'Flare of Long Night Flint',
                      'Blaze of Long Night Flint',
                      'Lost Glory of Far North Scion',
                      '迷顽 of Far North Scion',
                      '祷献 of Far North Scion',
                      '煌熠 of Far North Scion'],
 'character_boss_drop': ['Hurricane Seed',
                         'Lightning Prism',
                         'Basalt Pillar',
                         'Hoarfrost Core',
                         'Everflame Seed',
                         'Cleansing Heart',
                         'Juvenile Jade',
                         'Crystalline Bloom',
                         'Marionette Core',
                         'Perpetual Heart',
                         'Smoldering Pearl',
                         'Dew of Repudiation',
                         'Storm Beads',
                         'Riftborn Regalia',
                         "Dragonheir's False Fin",
                         'Runic Fang',
                         'Majestic Hooked Beak',
                         'Thunderclap Fruitcore',
                         'Perpetual Caliber',
                         'Light Guiding Tetrahedron',
                         'Quelled Creeper',
                         'Pseudo-Stamens',
                         'Evergloom Ring',
                         'Novel Spare Clockwork Component — Coppelia',
                         'Novel Spare Clockwork Component — Coppelius',
                         'Emperor’s Resolution',
                         'Tourbillon Device',
                         'Fontemer Unihorn',
                         'Water That Failed To Transcend',
                         'Cloudseam Scale',
                         'Fragment of a Golden Melody',
                         'Mark of the Binding Blessing',
                         'Overripe Flamegranate',
                         'Gold-Inscribed Secret Source Core',
                         'Ensnaring Gaze',
                         'Talisman of the Enigmatic Land',
                         'Sparkless Statue Core',
                         'Secret Source Airflow Accumulator'],
 'ascension_gem': ['Agnidus Agate Sliver',
                   'Agnidus Agate Fragment',
                   'Agnidus Agate Chunk',
                   'Agnidus Agate Gemstone',
                   'Varunada Lazurite Sliver',
                   'Varunada Lazurite Fragment',
                   'Varunada Lazurite Chunk',
                   'Varunada Lazurite Gemstone',
                   'Nagadus Emerald Sliver',
                   'Nagadus Emerald Fragment',
                   'Nagadus Emerald Chunk',
                   'Nagadus Emerald Gemstone',
                   'Vajrada Amethyst Sliver',
                   'Vajrada Amethyst Fragment',
                   'Vajrada Amethyst Chunk',
                   'Vajrada Amethyst Gemstone',
                   'Vayuda Turquoise Sliver',
                   'Vayuda Turquoise Fragment',
                   'Vayuda Turquoise Chunk',
                   'Vayuda Turquoise Gemstone',
                   'Shivada Jade Sliver',
                   'Shivada Jade Fragment',
                   'Shivada Jade Chunk',
                   'Shivada Jade Gemstone',
                   'Prithiva Topaz Sliver',
                   'Prithiva Topaz Fragment',
                   'Prithiva Topaz Chunk',
                   'Prithiva Topaz Gemstone',
                   'Brilliant Diamond Sliver',
                   'Brilliant Diamond Fragment',
                   'Brilliant Diamond Chunk',
                   'Brilliant Diamond Gemstone'],
 'local_specialty': ['Small Lamp Grass',
                     'Valberry',
                     'Wolfhook',
                     'Jueyun Chili',
                     'Noctilucous Jade',
                     'Windwheel Aster',
                     'Cor Lapis',
                     'Dandelion Seed',
                     'Calla Lily',
                     'Philanemo Mushroom',
                     'Silk Flower',
                     'Glaze Lily',
                     'Violetgrass',
                     'Cecilia',
                     'Starconch',
                     'Qingxin',
                     'Sea Ganoderma',
                     'Sakura Bloom',
                     'Naku Weed',
                     'Crystal Marrow',
                     'Amakumo Fruit',
                     'Dendrobium',
                     'Sango Pearl',
                     'Fluorescent Fungus',
                     'Onikabuto',
                     'Nilotpala Lotus',
                     'Rukkhashava Mushrooms',
                     'Kalpalata Lotus',
                     'Scarab',
                     'Henna Berry',
                     'Padisarah',
                     'Sand Grease Pupa',
                     'Mourning Flower',
                     'Rainbow Rose',
                     'Lumidouce Bell',
                     'Romaritime Flower',
                     'Lumitoile',
                     'Subdetection Unit',
                     'Lakelight Lily',
                     'Beryl Conch',
                     'Spring of the First Dewdrop',
                     'Clearwater Jade',
                     'Trishiraite',
                     'Sprayfeather Gill',
                     'Quenepa Berry',
                     'Saurian Claw Succulent',
                     'Brilliant Chrysanthemum',
                     'Withering Purpurbloom',
                     'Glowing Hornshroom',
                     'Skysplit Gembloom',
                     'Dracolite',
                     'Moonfall Silver',
                     'Frostcup Flower',
                     'Portable Bearing'],
 'weekly_boss_drop': ["Dvalin's Plume",
                      "Dvalin's Claw",
                      "Dvalin's Sigh",
                      'Tail of Boreas',
                      'Ring of Boreas',
                      'Spirit Locket of Boreas',
                      'Tusk of Monoceros Caeli',
                      'Shard of a Foul Legacy',
                      'Shadow of the Warrior',
                      "Dragon Lord's Crown",
                      'Bloodjade Branch',
                      'Gilded Scale',
                      'Molten Moment',
                      'Hellfire Butterfly',
                      'Ashen Heart',
                      'Mudra of the Malefic General',
                      'Tears of the Calamitous God',
                      'The Meaning of Aeons',
                      'Puppet Strings',
                      'Mirror of Mushin',
                      "Daka's Bell",
                      'Worldspan Fern',
                      'Primordial Greenbloom',
                      'Everamber',
                      'Lightless Silk String',
                      'Lightless Eye of the Maelstrom',
                      'Lightless Mass',
                      'Fading Candle',
                      'Silken Feather',
                      'Denial and Judgment',
                      'Eroded Horn',
                      'Eroded Sunfire',
                      'Eroded Scale-Feather',
                      'Ascended Sample: Knight',
                      'Ascended Sample: Rook',
                      'Ascended Sample: Queen']}
